### ISSUE TITLE
Readme repeats earlier content

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/testing-truth#2]
First part of readme repeats previous readme on truthiness

+readme cleanup: missing objectives, remove tag

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by SophieDeBenedetto** [comment]
hi @AnnJohn, this lab is deprecated and not being used. we can close the issue and do whatever it is we do to mark deprecated. Not sure if/how we mark something as deprecated actually...

**Comment by AnnJohn** [comment]
Lab deprecated so closing issue.
